# Generated by Django 5.0.4 on 2024-05-07 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_comment_posted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='uploads/news/banner/%d/%m/%Y/')),
                ('url', models.URLField()),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
